main.py: |-
  You changed main.py.

  I see you.
toto: "You touched toto!"
README:
  msg: "The README changed!"
  absent: false
CHANGELOG:
  msg: >-
    The CHANGELOG didn't change:
    
      * [ ] the CHANGELOG is edited
  absent: true
