name: Comment on diff
author: Alexandre Morignot <erdnaxeli@cervoi.se>
description: Add a comment on a PR depending on the diff
runs:
  using: 'docker'
  image: 'docker://erdnaxeli/comment-on-diff:latest'
