name: CI
on: [pull_request]
jobs:
  build:
    name: Run CI
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install env
        run: |
          pip install poetry
          poetry install
      - name: Tests
        run: |
          make test
      - name: Lint
        run: |
          make lint
