name: CI
on: [pull_request]
jobs:
  build:
    name: Run CI
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install env
        run: |
          pip install poetry
          poetry install --no-root
      - name: Tests
        run: |
          make test
      - name: Lint
        run: |
          make lint
