name: Publish
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Pubish
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Publish
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: erdnaxeli/comment-on-diff:latest
